language: 
  - cpp

os:
  - linux
  - osx
  
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5.4
      env: COMPILER=g++-5.4
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-5
          packages:
            - clang-5
      env: COMPILER=clang++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - src/Common/FenestrationCommon_tests
  - src/Gases/Gases_tests
  - src/SingleLayerOptics/SingleLayerOptics_tests
  - src/MultiLayerOptics/MultiLayerOptics_tests
  - src/SpectralAveraging/SpectralAveraging_tests
  - src/Tarcog/Tarcog_tests
  - src/Viewer/Viewer_tests
