language: 
  - cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - src/Common/FenestrationCommon_tests
  - src/Gases/Gases_tests
  - src/SingleLayerOptics/SingleLayerOptics_tests
  - src/MultiLayerOptics/MultiLayerOptics_tests
  - src/SpectralAveraging/SpectralAveraging_tests
  - src/Tarcog/Tarcog_tests
  - src/Viewer/Viewer_tests