language: 
  - cpp
  
compiler:
  - g++
  
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - src/Common/FenestrationCommon_tests
  - src/Gases/Gases_tests
  - src/LayerOptics/LayerOptics_tests
  - src/MultiPane/MultiPane_tests
  - src/SpectralAveraging/SpectralAveraging_tests
  - src/Tarcog/Tarcog_tests
  - src/Viewer/Viewer_tests